#![deny(warnings)]
// We call all macros in this module with `no_implicit_prelude` to ensure they do not depend on the standard prelude.
#![no_implicit_prelude]
extern crate tracing;
#[cfg(target_arch = "wasm32")]
extern crate wasm_bindgen_test;

use tracing::{
    Level, callsite, debug_internal, debug_span_internal, enabled, error_internal,
    error_span_internal, event_enabled, event_internal, info_internal, info_span_internal,
    span_enabled, span_internal, trace_internal, trace_span_internal, warn_internal,
    warn_span_internal,
};

// Tests that macros work across various invocation syntax.
//
// These are quite repetitive, and _could_ be generated by a macro. However,
// they're compile-time tests, so I want to get line numbers etc out of
// failures, and producing them with a macro would muddy the waters a bit.

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn span() {
    span_internal!(target: "foo_events", Level::DEBUG, "foo", bar.baz = ?2, quux = %3, quuux = 4);
    span_internal!(target: "foo_events", Level::DEBUG, "foo", bar.baz = 2, quux = 3);
    span_internal!(target: "foo_events", Level::DEBUG, "foo", bar.baz = 2, quux = 4,);
    span_internal!(target: "foo_events", Level::DEBUG, "foo");
    span_internal!(target: "foo_events", Level::DEBUG, "bar",);
    span_internal!(Level::DEBUG, "foo", bar.baz = 2, quux = 3);
    span_internal!(Level::DEBUG, "foo", bar.baz = 2, quux = 4,);
    span_internal!(Level::DEBUG, "foo", bar.baz = 2, quux = 3);
    span_internal!(Level::DEBUG, "foo", bar.baz = 2, quux = 4,);
    span_internal!(Level::DEBUG, "foo", bar.baz = ?2);
    span_internal!(Level::DEBUG, "foo", bar.baz = %2);
    span_internal!(Level::DEBUG, "foo");
    span_internal!(Level::DEBUG, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn trace_span() {
    trace_span_internal!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
    trace_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
    trace_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
    trace_span_internal!(target: "foo_events", "foo");
    trace_span_internal!(target: "foo_events", "bar",);
    trace_span_internal!("foo", bar.baz = 2, quux = 3);
    trace_span_internal!("foo", bar.baz = 2, quux = 4,);
    trace_span_internal!("foo", bar.baz = ?2);
    trace_span_internal!("foo", bar.baz = %2);
    trace_span_internal!("bar");
    trace_span_internal!("bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn debug_span() {
    debug_span_internal!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
    debug_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
    debug_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
    debug_span_internal!(target: "foo_events", "foo");
    debug_span_internal!(target: "foo_events", "bar",);
    debug_span_internal!("foo", bar.baz = 2, quux = 3);
    debug_span_internal!("foo", bar.baz = 2, quux = 4,);
    debug_span_internal!("foo", bar.baz = ?2);
    debug_span_internal!("foo", bar.baz = %2);
    debug_span_internal!("bar");
    debug_span_internal!("bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn info_span() {
    info_span_internal!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
    info_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
    info_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
    info_span_internal!(target: "foo_events", "foo");
    info_span_internal!(target: "foo_events", "bar",);
    info_span_internal!("foo", bar.baz = 2, quux = 3);
    info_span_internal!("foo", bar.baz = 2, quux = 4,);
    info_span_internal!("foo", bar.baz = ?2);
    info_span_internal!("foo", bar.baz = %2);
    info_span_internal!("bar");
    info_span_internal!("bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn warn_span() {
    warn_span_internal!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
    warn_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
    warn_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
    warn_span_internal!(target: "foo_events", "foo");
    warn_span_internal!(target: "foo_events", "bar",);
    warn_span_internal!("foo", bar.baz = 2, quux = 3);
    warn_span_internal!("foo", bar.baz = 2, quux = 4,);
    warn_span_internal!("foo", bar.baz = ?2);
    warn_span_internal!("foo", bar.baz = %2);
    warn_span_internal!("bar");
    warn_span_internal!("bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn error_span() {
    error_span_internal!(target: "foo_events", "foo", bar.baz = ?2, quux = %3, quuux = 4);
    error_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 3);
    error_span_internal!(target: "foo_events", "foo", bar.baz = 2, quux = 4,);
    error_span_internal!(target: "foo_events", "foo");
    error_span_internal!(target: "foo_events", "bar",);
    error_span_internal!("foo", bar.baz = 2, quux = 3);
    error_span_internal!("foo", bar.baz = 2, quux = 4,);
    error_span_internal!("foo", bar.baz = ?2);
    error_span_internal!("foo", bar.baz = %2);
    error_span_internal!("bar");
    error_span_internal!("bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn span_root() {
    span_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::TRACE, "foo", bar.baz = 2, quux = 3);
    span_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::TRACE, "foo", bar.baz = 2, quux = 3);
    span_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::TRACE, "foo", bar.baz = 2, quux = 4,);
    span_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::TRACE, "foo");
    span_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::TRACE, "bar",);
    span_internal!(
        parent: ::core::option::Option::None,
        Level::DEBUG,
        "foo",
        bar.baz = 2,
        quux = 3
    );
    span_internal!(
        parent: ::core::option::Option::None,
        Level::DEBUG,
        "foo",
        bar.baz = 2,
        quux = 4,
    );
    span_internal!(parent: ::core::option::Option::None, Level::DEBUG, "foo");
    span_internal!(parent: ::core::option::Option::None, Level::DEBUG, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn trace_span_root() {
    trace_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 3);
    trace_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 4,);
    trace_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    trace_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "bar",);
    trace_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 3
    );
    trace_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 4,
    );
    trace_span_internal!(parent: ::core::option::Option::None, "foo");
    trace_span_internal!(parent: ::core::option::Option::None, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn debug_span_root() {
    debug_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 3);
    debug_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 4,);
    debug_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    debug_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "bar",);
    debug_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 3
    );
    debug_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 4,
    );
    debug_span_internal!(parent: ::core::option::Option::None, "foo");
    debug_span_internal!(parent: ::core::option::Option::None, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn info_span_root() {
    info_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 3);
    info_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 4,);
    info_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    info_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "bar",);
    info_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 3
    );
    info_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 4,
    );
    info_span_internal!(parent: ::core::option::Option::None, "foo");
    info_span_internal!(parent: ::core::option::Option::None, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn warn_span_root() {
    warn_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 3);
    warn_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 4,);
    warn_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    warn_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "bar",);
    warn_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 3
    );
    warn_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 4,
    );
    warn_span_internal!(parent: ::core::option::Option::None, "foo");
    warn_span_internal!(parent: ::core::option::Option::None, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn error_span_root() {
    error_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 3);
    error_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo", bar.baz = 2, quux = 4,);
    error_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    error_span_internal!(target: "foo_events", parent: ::core::option::Option::None, "bar",);
    error_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 3
    );
    error_span_internal!(
        parent: ::core::option::Option::None,
        "foo",
        bar.baz = 2,
        quux = 4,
    );
    error_span_internal!(parent: ::core::option::Option::None, "foo");
    error_span_internal!(parent: ::core::option::Option::None, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn span_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    span_internal!(target: "foo_events", parent: &p, Level::TRACE, "foo", bar.baz = 2, quux = 3);
    span_internal!(target: "foo_events", parent: &p, Level::TRACE, "foo", bar.baz = 2, quux = 4,);
    span_internal!(target: "foo_events", parent: &p, Level::TRACE, "foo");
    span_internal!(target: "foo_events", parent: &p, Level::TRACE, "bar",);
    span_internal!(parent: &p, Level::DEBUG, "foo", bar.baz = 2, quux = 3);
    span_internal!(parent: &p, Level::DEBUG, "foo", bar.baz = 2, quux = 4,);
    span_internal!(parent: &p, Level::DEBUG, "foo");
    span_internal!(parent: &p, Level::DEBUG, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn trace_span_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    trace_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 3);
    trace_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 4,);
    trace_span_internal!(target: "foo_events", parent: &p, "foo");
    trace_span_internal!(target: "foo_events", parent: &p, "bar",);

    trace_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 3);
    trace_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 4,);

    trace_span_internal!(parent: &p, "foo");
    trace_span_internal!(parent: &p, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn debug_span_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    debug_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 3);
    debug_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 4,);
    debug_span_internal!(target: "foo_events", parent: &p, "foo");
    debug_span_internal!(target: "foo_events", parent: &p, "bar",);

    debug_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 3);
    debug_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 4,);

    debug_span_internal!(parent: &p, "foo");
    debug_span_internal!(parent: &p, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn info_span_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    info_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 3);
    info_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 4,);
    info_span_internal!(target: "foo_events", parent: &p, "foo");
    info_span_internal!(target: "foo_events", parent: &p, "bar",);

    info_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 3);
    info_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 4,);

    info_span_internal!(parent: &p, "foo");
    info_span_internal!(parent: &p, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn warn_span_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    warn_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 3);
    warn_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 4,);
    warn_span_internal!(target: "foo_events", parent: &p, "foo");
    warn_span_internal!(target: "foo_events", parent: &p, "bar",);

    warn_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 3);
    warn_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 4,);

    warn_span_internal!(parent: &p, "foo");
    warn_span_internal!(parent: &p, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn error_span_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    error_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 3);
    error_span_internal!(target: "foo_events", parent: &p, "foo", bar.baz = 2, quux = 4,);
    error_span_internal!(target: "foo_events", parent: &p, "foo");
    error_span_internal!(target: "foo_events", parent: &p, "bar",);

    error_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 3);
    error_span_internal!(parent: &p, "foo", bar.baz = 2, quux = 4,);

    error_span_internal!(parent: &p, "foo");
    error_span_internal!(parent: &p, "bar",);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn span_with_non_rust_symbol() {
    span_internal!(Level::TRACE, "non-rust", "guid:x-request-id" = ?"abcdef", "more {}", 42);
    span_internal!(Level::TRACE, "non-rust", "guid:x-request-id" = %"abcdef", "more {}", 51);
    span_internal!(
        Level::TRACE,
        "non-rust",
        "guid:x-request-id" = "abcdef",
        "more {}",
        60
    );
    span_internal!(Level::TRACE, "non-rust", "guid:x-request-id" = ?"abcdef");
    span_internal!(Level::TRACE, "non-rust", "guid:x-request-id" = %"abcdef");
    span_internal!(Level::TRACE, "non-rust", "guid:x-request-id" = "abcdef");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn large_span() {
    span_internal!(
        Level::TRACE,
        "spans with more than 32 fields have been supported since #2508",
        a = 1,
        b = 2,
        c = 3,
        d = 4,
        e = 5,
        f = 6,
        g = 7,
        h = 8,
        i = 9,
        j = 10,
        k = 11,
        l = 12,
        m = 13,
        n = 14,
        o = 15,
        p = 16,
        q = 17,
        r = 18,
        s = 19,
        t = 20,
        u = 21,
        v = 22,
        w = 23,
        x = 24,
        y = 25,
        z = 26,
        aa = 27,
        bb = 28,
        cc = 29,
        dd = 30,
        ee = 31,
        ff = 32,
        gg = 33
    );
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn event() {
    event_internal!(Level::DEBUG, foo = ?3, bar.baz = %2, quux = false);
    event_internal!(Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
    event_internal!(Level::DEBUG, foo = 3, bar.baz = 3,);
    event_internal!(Level::DEBUG, "foo");
    event_internal!(Level::DEBUG, "foo: {}", 3);
    event_internal!(Level::INFO, foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
    event_internal!(
        Level::INFO,
        foo = 3,
        bar.baz = 2,
        quux = false,
        "hello world {:?}",
        42
    );
    event_internal!(Level::INFO, foo = 3, bar.baz = 3, "hello world {:?}", 42,);
    event_internal!(Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
    event_internal!(Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    event_internal!(Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    event_internal!(Level::DEBUG, { foo = ?2, bar.baz = %78 }, "quux");
    event_internal!(target: "foo_events", Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
    event_internal!(target: "foo_events", Level::DEBUG, foo = 3, bar.baz = 3,);
    event_internal!(target: "foo_events", Level::DEBUG, "foo");
    event_internal!(target: "foo_events", Level::DEBUG, "foo: {}", 3);
    event_internal!(target: "foo_events", Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
    event_internal!(target: "foo_events", Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    event_internal!(target: "foo_events", Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    event_internal!(target: "foo_events", Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
    let foo = 1;
    event_internal!(Level::DEBUG, ?foo);
    event_internal!(Level::DEBUG, %foo);
    event_internal!(Level::DEBUG, foo);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn enabled() {
    enabled!(Level::DEBUG, foo, bar.baz, quux,);
    enabled!(Level::DEBUG, message);
    enabled!(Level::INFO, foo, bar.baz, quux, message,);
    enabled!(Level::INFO, foo, bar., message,);
    enabled!(Level::DEBUG, foo);

    enabled!(Level::DEBUG);
    enabled!(target: "rando", Level::DEBUG);
    enabled!(target: "rando", Level::DEBUG, field);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn span_enabled() {
    span_enabled!(Level::DEBUG, foo, bar.baz, quux,);
    span_enabled!(Level::DEBUG, message);
    span_enabled!(Level::INFO, foo, bar.baz, quux, message,);
    span_enabled!(Level::INFO, foo, bar., message,);
    span_enabled!(Level::DEBUG, foo);

    span_enabled!(Level::DEBUG);
    span_enabled!(target: "rando", Level::DEBUG);
    span_enabled!(target: "rando", Level::DEBUG, field);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn event_enabled() {
    event_enabled!(Level::DEBUG, foo, bar.baz, quux,);
    event_enabled!(Level::DEBUG, message);
    event_enabled!(Level::INFO, foo, bar.baz, quux, message,);
    event_enabled!(Level::INFO, foo, bar., message,);
    event_enabled!(Level::DEBUG, foo);

    event_enabled!(Level::DEBUG);
    event_enabled!(target: "rando", Level::DEBUG);
    event_enabled!(target: "rando", Level::DEBUG, field);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn locals_with_message() {
    let data = (42, "forty-two");
    let private_data = "private";
    let error = "a bad error";
    event_internal!(Level::ERROR, %error, "Received error");
    event_internal!(
        target: "app_events",
        Level::WARN,
        private_data,
        ?data,
        "App warning: {}",
        error
    );
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn locals_no_message() {
    let data = (42, "forty-two");
    let private_data = "private";
    let error = "a bad error";
    event_internal!(
        name: "foo",
        target: "app_events",
        Level::WARN,
        private_data,
        ?data,
    );
    event_internal!(
        target: "app_events",
        Level::WARN,
        private_data,
        ?data,
    );
    event_internal!(
        target: "app_events",
        Level::WARN,
        private_data,
        ?data,
        error,
    );
    event_internal!(
        target: "app_events",
        Level::WARN,
        private_data,
        ?data,
        error
    );
    event_internal!(Level::WARN, private_data, ?data, error,);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn trace() {
    trace_internal!(foo = ?3, bar.baz = %2, quux = false);
    trace_internal!(foo = 3, bar.baz = 2, quux = false);
    trace_internal!(foo = 3, bar.baz = 3,);
    trace_internal!("foo");
    trace_internal!("foo: {}", 3);
    trace_internal!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
    trace_internal!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
    trace_internal!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
    trace_internal!({ foo = 3, bar.baz = 80 }, "quux");
    trace_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
    trace_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    trace_internal!({ foo = 2, bar.baz = 78 }, "quux");
    trace_internal!({ foo = ?2, bar.baz = %78 }, "quux");
    trace_internal!(name: "foo", foo = 3, bar.baz = 2, quux = false);
    trace_internal!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    trace_internal!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    trace_internal!(target: "foo_events", foo = 3, bar.baz = 3,);
    trace_internal!(target: "foo_events", "foo");
    trace_internal!(target: "foo_events", "foo: {}", 3);
    trace_internal!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
    trace_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    trace_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    trace_internal!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
    let foo = 1;
    trace_internal!(?foo);
    trace_internal!(%foo);
    trace_internal!(foo);
    trace_internal!(name: "foo", ?foo);
    trace_internal!(name: "foo", %foo);
    trace_internal!(name: "foo", foo);
    trace_internal!(name: "foo", ?foo, true, "message");
    trace_internal!(name: "foo", %foo, true, "message");
    trace_internal!(name: "foo", foo, true, "message");
    trace_internal!(target: "foo_events", ?foo);
    trace_internal!(target: "foo_events", %foo);
    trace_internal!(target: "foo_events", foo);
    trace_internal!(target: "foo_events", ?foo, true, "message");
    trace_internal!(target: "foo_events", %foo, true, "message");
    trace_internal!(target: "foo_events", foo, true, "message");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn debug() {
    debug_internal!(foo = ?3, bar.baz = %2, quux = false);
    debug_internal!(foo = 3, bar.baz = 2, quux = false);
    debug_internal!(foo = 3, bar.baz = 3,);
    debug_internal!("foo");
    debug_internal!("foo: {}", 3);
    debug_internal!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
    debug_internal!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
    debug_internal!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
    debug_internal!({ foo = 3, bar.baz = 80 }, "quux");
    debug_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
    debug_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    debug_internal!({ foo = 2, bar.baz = 78 }, "quux");
    debug_internal!({ foo = ?2, bar.baz = %78 }, "quux");
    debug_internal!(name: "foo", foo = 3, bar.baz = 2, quux = false);
    debug_internal!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    debug_internal!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    debug_internal!(target: "foo_events", foo = 3, bar.baz = 3,);
    debug_internal!(target: "foo_events", "foo");
    debug_internal!(target: "foo_events", "foo: {}", 3);
    debug_internal!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
    debug_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    debug_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    debug_internal!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
    let foo = 1;
    debug_internal!(?foo);
    debug_internal!(%foo);
    debug_internal!(foo);
    debug_internal!(name: "foo", ?foo);
    debug_internal!(name: "foo", %foo);
    debug_internal!(name: "foo", foo);
    debug_internal!(name: "foo", ?foo, true, "message");
    debug_internal!(name: "foo", %foo, true, "message");
    debug_internal!(name: "foo", foo, true, "message");
    debug_internal!(target: "foo_events", ?foo);
    debug_internal!(target: "foo_events", %foo);
    debug_internal!(target: "foo_events", foo);
    debug_internal!(target: "foo_events", ?foo, true, "message");
    debug_internal!(target: "foo_events", %foo, true, "message");
    debug_internal!(target: "foo_events", foo, true, "message");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn info() {
    info_internal!(foo = ?3, bar.baz = %2, quux = false);
    info_internal!(foo = 3, bar.baz = 2, quux = false);
    info_internal!(foo = 3, bar.baz = 3,);
    info_internal!("foo");
    info_internal!("foo: {}", 3);
    info_internal!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
    info_internal!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
    info_internal!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
    info_internal!({ foo = 3, bar.baz = 80 }, "quux");
    info_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
    info_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    info_internal!({ foo = 2, bar.baz = 78 }, "quux");
    info_internal!({ foo = ?2, bar.baz = %78 }, "quux");
    info_internal!(name: "foo", foo = 3, bar.baz = 2, quux = false);
    info_internal!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    info_internal!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    info_internal!(target: "foo_events", foo = 3, bar.baz = 3,);
    info_internal!(target: "foo_events", "foo");
    info_internal!(target: "foo_events", "foo: {}", 3);
    info_internal!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
    info_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    info_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    info_internal!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
    let foo = 1;
    info_internal!(?foo);
    info_internal!(%foo);
    info_internal!(foo);
    info_internal!(name: "foo", ?foo);
    info_internal!(name: "foo", %foo);
    info_internal!(name: "foo", foo);
    info_internal!(name: "foo", ?foo, true, "message");
    info_internal!(name: "foo", %foo, true, "message");
    info_internal!(name: "foo", foo, true, "message");
    info_internal!(target: "foo_events", ?foo);
    info_internal!(target: "foo_events", %foo);
    info_internal!(target: "foo_events", foo);
    info_internal!(target: "foo_events", ?foo, true, "message");
    info_internal!(target: "foo_events", %foo, true, "message");
    info_internal!(target: "foo_events", foo, true, "message");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn warn() {
    warn_internal!(foo = ?3, bar.baz = %2, quux = false);
    warn_internal!(foo = 3, bar.baz = 2, quux = false);
    warn_internal!(foo = 3, bar.baz = 3,);
    warn_internal!("foo");
    warn_internal!("foo: {}", 3);
    warn_internal!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
    warn_internal!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
    warn_internal!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
    warn_internal!({ foo = 3, bar.baz = 80 }, "quux");
    warn_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
    warn_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    warn_internal!({ foo = 2, bar.baz = 78 }, "quux");
    warn_internal!({ foo = ?2, bar.baz = %78 }, "quux");
    warn_internal!(name: "foo", foo = 3, bar.baz = 2, quux = false);
    warn_internal!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    warn_internal!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    warn_internal!(target: "foo_events", foo = 3, bar.baz = 3,);
    warn_internal!(target: "foo_events", "foo");
    warn_internal!(target: "foo_events", "foo: {}", 3);
    warn_internal!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
    warn_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    warn_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    warn_internal!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
    let foo = 1;
    warn_internal!(?foo);
    warn_internal!(%foo);
    warn_internal!(foo);
    warn_internal!(name: "foo", ?foo);
    warn_internal!(name: "foo", %foo);
    warn_internal!(name: "foo", foo);
    warn_internal!(name: "foo", ?foo, true, "message");
    warn_internal!(name: "foo", %foo, true, "message");
    warn_internal!(name: "foo", foo, true, "message");
    warn_internal!(target: "foo_events", ?foo);
    warn_internal!(target: "foo_events", %foo);
    warn_internal!(target: "foo_events", foo);
    warn_internal!(target: "foo_events", ?foo, true, "message");
    warn_internal!(target: "foo_events", %foo, true, "message");
    warn_internal!(target: "foo_events", foo, true, "message");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn error() {
    error_internal!(foo = ?3, bar.baz = %2, quux = false);
    error_internal!(foo = 3, bar.baz = 2, quux = false);
    error_internal!(foo = 3, bar.baz = 3,);
    error_internal!("foo");
    error_internal!("foo: {}", 3);
    error_internal!(foo = ?3, bar.baz = %2, quux = false, "hello world {:?}", 42);
    error_internal!(foo = 3, bar.baz = 2, quux = false, "hello world {:?}", 42);
    error_internal!(foo = 3, bar.baz = 3, "hello world {:?}", 42,);
    error_internal!({ foo = 3, bar.baz = 80 }, "quux");
    error_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}", true);
    error_internal!({ foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    error_internal!({ foo = 2, bar.baz = 78, }, "quux");
    error_internal!({ foo = ?2, bar.baz = %78 }, "quux");
    error_internal!(name: "foo", foo = 3, bar.baz = 2, quux = false);
    error_internal!(name: "foo", target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    error_internal!(target: "foo_events", foo = 3, bar.baz = 2, quux = false);
    error_internal!(target: "foo_events", foo = 3, bar.baz = 3,);
    error_internal!(target: "foo_events", "foo");
    error_internal!(target: "foo_events", "foo: {}", 3);
    error_internal!(target: "foo_events", { foo = 3, bar.baz = 80 }, "quux");
    error_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    error_internal!(target: "foo_events", { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    error_internal!(target: "foo_events", { foo = 2, bar.baz = 78, }, "quux");
    let foo = 1;
    error_internal!(?foo);
    error_internal!(%foo);
    error_internal!(foo);
    error_internal!(name: "foo", ?foo);
    error_internal!(name: "foo", %foo);
    error_internal!(name: "foo", foo);
    error_internal!(name: "foo", ?foo, true, "message");
    error_internal!(name: "foo", %foo, true, "message");
    error_internal!(name: "foo", foo, true, "message");
    error_internal!(target: "foo_events", ?foo);
    error_internal!(target: "foo_events", %foo);
    error_internal!(target: "foo_events", foo);
    error_internal!(target: "foo_events", ?foo, true, "message");
    error_internal!(target: "foo_events", %foo, true, "message");
    error_internal!(target: "foo_events", foo, true, "message");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn event_root() {
    event_internal!(parent: ::core::option::Option::None, Level::DEBUG, foo = ?3, bar.baz = %2, quux = false);
    event_internal!(
        parent: ::core::option::Option::None,
        Level::DEBUG,
        foo = 3,
        bar.baz = 2,
        quux = false
    );
    event_internal!(
        parent: ::core::option::Option::None,
        Level::DEBUG,
        foo = 3,
        bar.baz = 3,
    );
    event_internal!(parent: ::core::option::Option::None, Level::DEBUG, "foo");
    event_internal!(
        parent: ::core::option::Option::None,
        Level::DEBUG,
        "foo: {}",
        3
    );
    event_internal!(parent: ::core::option::Option::None, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
    event_internal!(parent: ::core::option::Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    event_internal!(parent: ::core::option::Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    event_internal!(parent: ::core::option::Option::None, Level::DEBUG, { foo = ?2, bar.baz = %78 }, "quux");
    event_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
    event_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, foo = 3, bar.baz = 3,);
    event_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, "foo");
    event_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, "foo: {}", 3);
    event_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
    event_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    event_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    event_internal!(target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
    event_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
    event_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, foo = 3, bar.baz = 3,);
    event_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, "foo");
    event_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, "foo: {}", 3);
    event_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
    event_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    event_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    event_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn trace_root() {
    trace_internal!(parent: ::core::option::Option::None, foo = ?3, bar.baz = %2, quux = false);
    trace_internal!(
        parent: ::core::option::Option::None,
        foo = 3,
        bar.baz = 2,
        quux = false
    );
    trace_internal!(parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    trace_internal!(parent: ::core::option::Option::None, "foo");
    trace_internal!(parent: ::core::option::Option::None, "foo: {}", 3);
    trace_internal!(parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    trace_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    trace_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    trace_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 78 }, "quux");
    trace_internal!(parent: ::core::option::Option::None, { foo = ?2, bar.baz = %78 }, "quux");
    trace_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    trace_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    trace_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    trace_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    trace_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    trace_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    trace_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    trace_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
    trace_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    trace_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    trace_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo");
    trace_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    trace_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    trace_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    trace_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    trace_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn debug_root() {
    debug_internal!(parent: ::core::option::Option::None, foo = ?3, bar.baz = %2, quux = false);
    debug_internal!(
        parent: ::core::option::Option::None,
        foo = 3,
        bar.baz = 2,
        quux = false
    );
    debug_internal!(parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    debug_internal!(parent: ::core::option::Option::None, "foo");
    debug_internal!(parent: ::core::option::Option::None, "foo: {}", 3);
    debug_internal!(parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    debug_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    debug_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    debug_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 78 }, "quux");
    debug_internal!(parent: ::core::option::Option::None, { foo = ?2, bar.baz = %78 }, "quux");
    debug_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    debug_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    debug_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    debug_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    debug_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    debug_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    debug_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    debug_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
    debug_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    debug_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    debug_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo");
    debug_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    debug_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    debug_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    debug_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    debug_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn info_root() {
    info_internal!(parent: ::core::option::Option::None, foo = ?3, bar.baz = %2, quux = false);
    info_internal!(
        parent: ::core::option::Option::None,
        foo = 3,
        bar.baz = 2,
        quux = false
    );
    info_internal!(parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    info_internal!(parent: ::core::option::Option::None, "foo");
    info_internal!(parent: ::core::option::Option::None, "foo: {}", 3);
    info_internal!(parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    info_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    info_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    info_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 78 }, "quux");
    info_internal!(parent: ::core::option::Option::None, { foo = ?2, bar.baz = %78 }, "quux");
    info_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    info_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    info_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    info_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    info_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    info_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    info_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    info_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
    info_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    info_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    info_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo");
    info_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    info_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    info_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    info_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    info_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn warn_root() {
    warn_internal!(parent: ::core::option::Option::None, foo = ?3, bar.baz = %2, quux = false);
    warn_internal!(
        parent: ::core::option::Option::None,
        foo = 3,
        bar.baz = 2,
        quux = false
    );
    warn_internal!(parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    warn_internal!(parent: ::core::option::Option::None, "foo");
    warn_internal!(parent: ::core::option::Option::None, "foo: {}", 3);
    warn_internal!(parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    warn_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    warn_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    warn_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 78 }, "quux");
    warn_internal!(parent: ::core::option::Option::None, { foo = ?2, bar.baz = %78 }, "quux");
    warn_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    warn_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    warn_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    warn_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    warn_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    warn_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    warn_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    warn_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
    warn_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    warn_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    warn_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo");
    warn_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    warn_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    warn_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    warn_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    warn_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn error_root() {
    error_internal!(parent: ::core::option::Option::None, foo = ?3, bar.baz = %2, quux = false);
    error_internal!(
        parent: ::core::option::Option::None,
        foo = 3,
        bar.baz = 2,
        quux = false
    );
    error_internal!(parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    error_internal!(parent: ::core::option::Option::None, "foo");
    error_internal!(parent: ::core::option::Option::None, "foo: {}", 3);
    error_internal!(parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    error_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    error_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    error_internal!(parent: ::core::option::Option::None, { foo = 2, bar.baz = 78 }, "quux");
    error_internal!(parent: ::core::option::Option::None, { foo = ?2, bar.baz = %78 }, "quux");
    error_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    error_internal!(target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    error_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo");
    error_internal!(target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    error_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    error_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    error_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    error_internal!(target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
    error_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 2, quux = false);
    error_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, foo = 3, bar.baz = 3,);
    error_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo");
    error_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, "foo: {}", 3);
    error_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 3, bar.baz = 80 }, "quux");
    error_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    error_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    error_internal!(name: "foo", target: "foo_events", parent: ::core::option::Option::None, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn event_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    event_internal!(parent: &p, Level::DEBUG, foo = ?3, bar.baz = %2, quux = false);
    event_internal!(parent: &p, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
    event_internal!(parent: &p, Level::DEBUG, foo = 3, bar.baz = 3,);
    event_internal!(parent: &p, Level::DEBUG, "foo");
    event_internal!(parent: &p, Level::DEBUG, "foo: {}", 3);
    event_internal!(parent: &p, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
    event_internal!(parent: &p, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    event_internal!(parent: &p, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    event_internal!(parent: &p, Level::DEBUG, { foo = ?2, bar.baz = %78 }, "quux");
    event_internal!(target: "foo_events", parent: &p, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
    event_internal!(target: "foo_events", parent: &p, Level::DEBUG, foo = 3, bar.baz = 3,);
    event_internal!(target: "foo_events", parent: &p, Level::DEBUG, "foo");
    event_internal!(target: "foo_events", parent: &p, Level::DEBUG, "foo: {}", 3);
    event_internal!(target: "foo_events", parent: &p, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
    event_internal!(target: "foo_events", parent: &p, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    event_internal!(target: "foo_events", parent: &p, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    event_internal!(target: "foo_events", parent: &p, Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
    event_internal!(name: "foo", target: "foo_events", parent: &p, Level::DEBUG, foo = 3, bar.baz = 2, quux = false);
    event_internal!(name: "foo", target: "foo_events", parent: &p, Level::DEBUG, foo = 3, bar.baz = 3,);
    event_internal!(name: "foo", target: "foo_events", parent: &p, Level::DEBUG, "foo");
    event_internal!(name: "foo", target: "foo_events", parent: &p, Level::DEBUG, "foo: {}", 3);
    event_internal!(name: "foo", target: "foo_events", parent: &p, Level::DEBUG, { foo = 3, bar.baz = 80 }, "quux");
    event_internal!(name: "foo", target: "foo_events", parent: &p, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    event_internal!(name: "foo", target: "foo_events", parent: &p, Level::DEBUG, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    event_internal!(name: "foo", target: "foo_events", parent: &p, Level::DEBUG, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn trace_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    trace_internal!(parent: &p, foo = ?3, bar.baz = %2, quux = false);
    trace_internal!(parent: &p, foo = 3, bar.baz = 2, quux = false);
    trace_internal!(parent: &p, foo = 3, bar.baz = 3,);
    trace_internal!(parent: &p, "foo");
    trace_internal!(parent: &p, "foo: {}", 3);
    trace_internal!(parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    trace_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    trace_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    trace_internal!(parent: &p, { foo = 2, bar.baz = 78 }, "quux");
    trace_internal!(parent: &p, { foo = ?2, bar.baz = %78 }, "quux");
    trace_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    trace_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    trace_internal!(target: "foo_events", parent: &p, "foo");
    trace_internal!(target: "foo_events", parent: &p, "foo: {}", 3);
    trace_internal!(target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    trace_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    trace_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    trace_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
    trace_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    trace_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    trace_internal!(name: "foo", target: "foo_events", parent: &p, "foo");
    trace_internal!(name: "foo", target: "foo_events", parent: &p, "foo: {}", 3);
    trace_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    trace_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    trace_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    trace_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn debug_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    debug_internal!(parent: &p, foo = ?3, bar.baz = %2, quux = false);
    debug_internal!(parent: &p, foo = 3, bar.baz = 2, quux = false);
    debug_internal!(parent: &p, foo = 3, bar.baz = 3,);
    debug_internal!(parent: &p, "foo");
    debug_internal!(parent: &p, "foo: {}", 3);
    debug_internal!(parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    debug_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    debug_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    debug_internal!(parent: &p, { foo = 2, bar.baz = 78 }, "quux");
    debug_internal!(parent: &p, { foo = ?2, bar.baz = %78 }, "quux");
    debug_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    debug_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    debug_internal!(target: "foo_events", parent: &p, "foo");
    debug_internal!(target: "foo_events", parent: &p, "foo: {}", 3);
    debug_internal!(target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    debug_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    debug_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    debug_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
    debug_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    debug_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    debug_internal!(name: "foo", target: "foo_events", parent: &p, "foo");
    debug_internal!(name: "foo", target: "foo_events", parent: &p, "foo: {}", 3);
    debug_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    debug_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    debug_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    debug_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn info_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    info_internal!(parent: &p, foo = ?3, bar.baz = %2, quux = false);
    info_internal!(parent: &p, foo = 3, bar.baz = 2, quux = false);
    info_internal!(parent: &p, foo = 3, bar.baz = 3,);
    info_internal!(parent: &p, "foo");
    info_internal!(parent: &p, "foo: {}", 3);
    info_internal!(parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    info_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    info_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    info_internal!(parent: &p, { foo = 2, bar.baz = 78 }, "quux");
    info_internal!(parent: &p, { foo = ?2, bar.baz = %78 }, "quux");
    info_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    info_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    info_internal!(target: "foo_events", parent: &p, "foo");
    info_internal!(target: "foo_events", parent: &p, "foo: {}", 3);
    info_internal!(target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    info_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    info_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    info_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
    info_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    info_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    info_internal!(name: "foo", target: "foo_events", parent: &p, "foo");
    info_internal!(name: "foo", target: "foo_events", parent: &p, "foo: {}", 3);
    info_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    info_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    info_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    info_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn warn_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    warn_internal!(parent: &p, foo = ?3, bar.baz = %2, quux = false);
    warn_internal!(parent: &p, foo = 3, bar.baz = 2, quux = false);
    warn_internal!(parent: &p, foo = 3, bar.baz = 3,);
    warn_internal!(parent: &p, "foo");
    warn_internal!(parent: &p, "foo: {}", 3);
    warn_internal!(parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    warn_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    warn_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    warn_internal!(parent: &p, { foo = 2, bar.baz = 78 }, "quux");
    warn_internal!(parent: &p, { foo = ?2, bar.baz = %78 }, "quux");
    warn_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    warn_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    warn_internal!(target: "foo_events", parent: &p, "foo");
    warn_internal!(target: "foo_events", parent: &p, "foo: {}", 3);
    warn_internal!(target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    warn_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    warn_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    warn_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
    warn_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    warn_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    warn_internal!(name: "foo", target: "foo_events", parent: &p, "foo");
    warn_internal!(name: "foo", target: "foo_events", parent: &p, "foo: {}", 3);
    warn_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    warn_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    warn_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    warn_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn error_with_parent() {
    let p = span_internal!(Level::TRACE, "im_a_parent!");
    error_internal!(parent: &p, foo = ?3, bar.baz = %2, quux = false);
    error_internal!(parent: &p, foo = 3, bar.baz = 2, quux = false);
    error_internal!(parent: &p, foo = 3, bar.baz = 3,);
    error_internal!(parent: &p, "foo");
    error_internal!(parent: &p, "foo: {}", 3);
    error_internal!(parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    error_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    error_internal!(parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    error_internal!(parent: &p, { foo = 2, bar.baz = 78 }, "quux");
    error_internal!(parent: &p, { foo = ?2, bar.baz = %78 }, "quux");
    error_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    error_internal!(target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    error_internal!(target: "foo_events", parent: &p, "foo");
    error_internal!(target: "foo_events", parent: &p, "foo: {}", 3);
    error_internal!(target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    error_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    error_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    error_internal!(target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
    error_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 2, quux = false);
    error_internal!(name: "foo", target: "foo_events", parent: &p, foo = 3, bar.baz = 3,);
    error_internal!(name: "foo", target: "foo_events", parent: &p, "foo");
    error_internal!(name: "foo", target: "foo_events", parent: &p, "foo: {}", 3);
    error_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 3, bar.baz = 80 }, "quux");
    error_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}", true);
    error_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 79 }, "quux {:?}, {quux}", true, quux = false);
    error_internal!(name: "foo", target: "foo_events", parent: &p, { foo = 2, bar.baz = 78, }, "quux");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn field_shorthand_only() {
    #[derive(Debug)]
    struct Position {
        x: f32,
        y: f32,
    }
    let pos = Position {
        x: 3.234,
        y: -1.223,
    };

    trace_internal!(?pos.x, ?pos.y);
    debug_internal!(?pos.x, ?pos.y);
    info_internal!(?pos.x, ?pos.y);
    warn_internal!(?pos.x, ?pos.y);
    error_internal!(?pos.x, ?pos.y);
    event_internal!(Level::TRACE, ?pos.x, ?pos.y);
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn borrow_val_events() {
    // Reproduces https://github.com/tokio-rs/tracing/issues/954
    let mut foo = (::std::string::String::new(), ::std::string::String::new());
    let zero = &mut foo.0;
    trace_internal!(one = ?foo.1);
    debug_internal!(one = ?foo.1);
    info_internal!(one = ?foo.1);
    warn_internal!(one = ?foo.1);
    error_internal!(one = ?foo.1);
    zero.push_str("hello world");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn borrow_val_spans() {
    // Reproduces https://github.com/tokio-rs/tracing/issues/954
    let mut foo = (::std::string::String::new(), ::std::string::String::new());
    let zero = &mut foo.0;
    let _span = trace_span_internal!("span", one = ?foo.1);
    let _span = debug_span_internal!("span", one = ?foo.1);
    let _span = info_span_internal!("span", one = ?foo.1);
    let _span = warn_span_internal!("span", one = ?foo.1);
    let _span = error_span_internal!("span", one = ?foo.1);
    zero.push_str("hello world");
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn callsite_macro_api() {
    // This test should catch any inadvertent breaking changes
    // caused by changes to the macro.
    let _callsite = callsite! {
        name: "test callsite",
        kind: tracing::metadata::Kind::EVENT,
        target: "test target",
        level: tracing::Level::TRACE,
        fields: foo, bar,
    };
    let _callsite = callsite! {
        name: "test callsite",
        kind: tracing::metadata::Kind::SPAN,
        level: tracing::Level::TRACE,
        fields: foo,
    };
    let _callsite = callsite! {
        name: "test callsite",
        kind: tracing::metadata::Kind::SPAN,
        fields: foo,
    };
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test::wasm_bindgen_test)]
#[test]
fn format_args_already_defined() {
    // Reproduces: https://github.com/tokio-rs/tracing/issues/2721
    #[allow(unused)]
    macro_rules! format_args {
        ($i:expr) => {};
    }
    event_internal!(Level::DEBUG, "foo: {}", 3);
    trace_internal!("foo: {}", 3);
    debug_internal!("foo: {}", 3);
    info_internal!("foo: {}", 3);
    warn_internal!("foo: {}", 3);
    error_internal!("foo: {}", 3);
}
